-- 1. 

CREATE VIEW STATISTIKA_RADNIH_MESTA
AS SELECT ZAPOSLENI.IME, ZAPOSLENI.PREZIME, COUNT(DISTINCT ISTORIJA_RADNIH_MESTA.ID_R_MESTO) AS BROJ_RAZLICITH_POZICIJA, SUM(iSTORIJA_RADNIH_MESTA.DATUM_KRAJA - ISTORIJA_RADNIH_MESTA.DATUM_POC) AS UKUPAN_BROJ_DANA
FROM ZAPOSLENI INNER JOIN ISTORIJA_RADNIH_MESTA ON ZAPOSLENI.ID = ISTORIJA_RADNIH_MESTA.ID_ZAP
INNER JOIN RADNO_MESTO ON ISTORIJA_RADNIH_MESTA.ID_R_MESTO = RADNO_MESTO.ID
GROUP BY ZAPOSLENI.IME, ZAPOSLENI.PREZIME

SELECT ZAPOSLENI.IME, ZAPOSLENI.PREZIME, ZAPOSLENI.ID
FROM STATISTIKA_RADNIH_MESTA
WHERE BROJ_RAZLICITIH_POZICIJA >= 2
AND
UKUPAN_BROJ_DANA > 100;

-- 2. 

UPDATE ZAPOSLENI
SET PLATA = PLATA * 1,15
WHERE ZAPOSLENI.ID IN (SELECT ZAPOSLENI.ID
FROM ZAPOSLENI
INNER JOIN RADNO_MESTO ON ZAPOSLENI.ID_R_MESTO = RADNO_MESTO.ID
INNER JOIN ODELJENJE ON ZAPOSLENI.ID_ODELJENJE = ODELJENJE.ID
WHERE RADNO_MESTO.MAX_PLATA < 70000
GROUP BY ZAPOSLENI.ID_ODELJENJE
HAVING COUNT(ZAPOSLENI.ID) >= 2);

-- 3. 

DELETE FROM ISTORIJA_RADNIH_MESTA
WHERE ISTORIJA_RADNIH_MESTA.ID_R_MESTO IN (SELECT ISTORIJA_RADNIH_MESTA.ID_R_MESTO
FROM ISTORIJA_RADNIH_MESTA.
INNER JOIN ZAPOSLENI ON ISTORIJA_RADNIH_MESTA.ID_ZAP = ZAPOSLENI.ID
WHERE ZAPOSLENI.ID IS NULL);

