-- 1. 
CREATE VIEW STATISTIKA_ZAPOSLENI
AS SELECT ZAPOSLENI.IME, ZAPOSLENI.PREZIME, COUNT(DISTINCT RADNO_MESTO.POZICIJA) AS BR_RAZLICITH_POZICIJA,
AVG(CASE WHEN RADNO_MESTO.DATUMDO IS NOT NULL THEN RADNO_MESTO.DATUMOD - RADNO_MESTO.DATUMDO END) AS PROSECNO_VREME
FROM ZAPOSLENI INNER JOIN RADNO_MESTO ON ZAPOSLENI.JMBG = RADNO_MESTO.ZJMBG
WHERE ZAPOSLENI.DATUMDO IS NULL
GROUP BY ZAPOSLENI.IME, ZAPOSLENI.PREZIME

SELECT * FROM STATISTIKA_ZAPOSLENI
WHERE BR_RAZLICITIH >= 2 AND PROSECNO_VREME > 300;

-- 2.

UPDATE ZAPOSLENI
SET ZAPOSLENI.PLATA = ZAPOSLENI.PLATA * 1.15 -- POVECANJE PLATE ZA 15%
WHERE ZAPOSLENI.JMBG IN (SELECT RADNO_MESTO.ZJMBG
  FROM ZAPOSLENI INNER JOIN RADNO_MESTO ON RADNO_MESTO.ZJMBG = ZAPOSLENI.JMBG
  INNER JOIN KOMPANIJA ON RADNO_MESTO.IDK = KOMPANIJA.IDK 
  WHERE RADNO_MESTO.DATUMDO IS NOT NULL AND KOMPANIJA.ADRESA = 'NIS'
  GROUP BY RADNO_MESTO.ZJMBG
  HAVING COUNT(DISTINCT RADNO_MESTO.POZICIJA) >= 1;

-- 3

DELETE 
FROM RADNO_MESTO
WHERE RADNO_MESTO.ZJMBG IN (
    SELECT ZAPOSLENI.JMBG
    FROM ZAPOSLENI
    INNER JOIN RADNO_MESTO ON ZAPOSLENI.JMBG = RADNO_MESTO.ZJMBG
    INNER JOIN KOMPANIJA ON RADNO_MESTO.IDK = KOMPANIJA.IDK
    WHERE KOMPANIJA.GODINA_OSN < 2000
    GROUP BY ZAPOSLENI.JMBG
    HAVING SUM(CASE WHEN RADNO_MESTO.DATUMDO IS NOT NULL THEN RADNO_MESTO.DATUMDO - RADNO_MESTO.DATUMOD
    ELSE SYSDATE-DATUMDO END) > 1000
);
  
