
-- 2. A)

CREATE VIEW STATISTIKA
AS SELECT SPORTISTA.IME, SPORTISTA.PREZIME, SPORTISTA.GOD_ROD, SPORTISTA.PLATA, COUNT(CLAN.ID_KLUBA) AS BROJ_KLUBOVA
FROM SPORTISTA
INNER JOIN CLAN ON SPORTISTA.ID = CLAN.ID_SPORTISTE
INNER JOIN KLUB ON CLAN.ID_KLUBA = KLUB.ID
GROUP BY SPORTISTA.IME, SPORTISTA.PREZIME, SPORTISTA.GOD_ROD, SPORTISTIA.PLATA

SELECT *
FROM STATISTIKA
WHERE BROJ_KLUBOVA >=2

-- 2. B)

UPDATE SPORTISTA
SET PLATA = PLATA * 0,97
WHERE ID IN (SELECT CLAN.ID_SPORTISTE
FROM CLAN
INNER JOIN KLUB ON CLAN.ID_KLUBA = KLUB.ID
WHERE CLAN.TIM = 'PRVI'
AND KLUB.SPORT = 'ODBOJKA'
AND KLUB.LOKACIJA = 'NOVI SAD');

-- 3. c)

